# Generated by Django 4.0.3 on 2022-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default=False, upload_to='p_images'),
        ),
    ]
