# Generated by Django 4.0.3 on 2022-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_blogs_image_blogs_blog_image_alter_blogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
