# Generated by Django 4.0.3 on 2022-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_rename_blog_image_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default=False, upload_to='blog_images'),
        ),
    ]
