# Generated by Django 4.0.3 on 2022-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_alter_blogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
