# Generated by Django 4.0.3 on 2022-05-14 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_alter_blogs_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
